#!/usr/bin/env python
# -*- coding: utf-8 -*-

import connector
import createInsertData as cid
import time
from random import randint, seed

seed(0)



# Create Schemata:

def create_table (table_name, table_type, columns, primary_keys):
    column_query = " NVARCHAR(20), ".join(columns) + " NVARCHAR(20), "
    primary_key_query = ", ".join(primary_keys)
    query = "create %s table %s (%s PRIMARY KEY(%s));" % (table_type, table_name, column_query, primary_key_query)
    connector.execute(query)

def dummy_insert(table_name, columns):
    values = ",".join([ str(randint(0, 100)) for i in range(len(columns))])
    query = "INSERT INTO %s VALUES(%s)" % (table_name, values)
    connector.execute(query)

def insert(table_name, values):
    query = "INSERT INTO %s VALUES(%s)" % (table_name, values)
    connector.execute(query)

# TODO needs to be defined
def update(table_name, values, columns):
    return   

def benchmark(iterations, fun, *args):
    start = time.time()
    for x in range(0, iterations):
        fun( *args )
    end = time.time()
    total_time = end - start
    iteration_time= total_time / iterations
    print ("Total time %.2fs, %.2fs average per iteration" % (total_time, iteration_time))

def benchmark_old_schema(iterations, data):
    start = time.time()
    for x in range(0, iterations):
        print(x,"iteration", data[x]['BKPF'])
        insert(schema_old + ".BKPF_R", data[x]['BKPF'])
        insert(schema_old + ".BSEG_R", data[x]['BSEG1'])
        insert(schema_old + ".BSEG_R", data[x]['BSEG2'])
    end = time.time()
    total_time = end - start
    iteration_time= total_time / iterations
    print ("Total time %.2fs, %.2fs average per iteration" % (total_time, iteration_time))    

bkpf_columns = [ "MANDT","BUKRS","BELNR","GJAHR","BLART","BLDAT","BUDAT","MONAT","CPUDT","CPUTM","AEDAT","UPDDT","WWERT","USNAM","TCODE","BVORG","XBLNR","DBBLG","STBLG","STJAH","BKTXT","WAERS","KURSF","KZWRS","KZKRS","BSTAT","XNETB","FRATH","XRUEB","GLVOR","GRPID","DOKID","ARCID","IBLAR","AWTYP","AWKEY","FIKRS","HWAER","HWAE2","HWAE3","KURS2","KURS3","BASW2","BASW3","UMRD2","UMRD3","XSTOV","STODT","XMWST","CURT2","CURT3","KUTY2","KUTY3","XSNET","AUSBK","XUSVR","DUEFL","AWSYS","TXKRS","LOTKZ","XWVOF","STGRD","PPNAM","BRNCH","NUMPG","ADISC","XREF1_HD","XREF2_HD","XREVERSAL","REINDAT","RLDNR","LDGRP","PROPMANO","XBLNR_ALT","VATDATE","PSOTY","PSOAK","PSOKS","PSOSG","PSOFN","INTFORM","INTDATE","PSOBT","PSOZL","PSODT","PSOTM","FM_UMART","CCINS","CCNUM","SSBLK","BATCH","SNAME","SAMPLED","EXCLUDE_FLAG","BLIND","OFFSET_STATUS","OFFSET_REFER_DAT","PENRC","KNUMV"]
bkpf_primary_keys = ["MANDT","BUKRS","BELNR","GJAHR"]

bkpf_reduced =  [ "MANDT","BUKRS","BELNR","GJAHR","BUDAT","MONAT", "WAERS", "KZWRS","KZKRS","HWAER"]
bseg_reduced = [ "MANDT","BUKRS","BELNR","GJAHR","BUZEI","GSBER","SHKZG","DMBTR","WRBRT","MWSTS","KOKRS","KOSTL","SAKNR","HKONT","KUNNR","MATNR","WERKS","MENGE","MEINS","AUFNR","PRCTR", "SEGMENT", "VBELN", "VBEL2", "KSTAR"]
glt0_reduced = [ "MANDT","RLDNR","BUKRS","GJAHR","RACCT","GSBER","SHKZG","RPMAX","HSL01","HSLVT","KSL01","KSLVT"]
acdoca_reduced = ["RCLNT","RLDNR","RBURKS","GJAHR","BELNR","DOCLN","RYEAR","AWREF","RHCUR","RVUNIT","RACCT","RCNTR","PRCTR","RBUSA","KOKRS","SEGMENT","SCNTR","PPRCTR","SBUSA","PSEGMENT","HSL","KSL","MSL","DRCRK","POPER","FISCYEARPER","BUDAT","BILDAT","KTOPL","REBZUG","REBZJ","REBZZ","KDAUF","KDPOS","MATNR","WERKS","LIFNR","KUNNR"]

# TODO select correct keys
acdoca_primary_keys = ["RCLNT"]
glt0_primary_keys = ["MANDT"]

bseg_columns = [ "MANDT","BUKRS","BELNR","GJAHR","BUZEI","BUZID","AUGDT","AUGCP","AUGBL","BSCHL","KOART","UMSKZ","UMSKS","ZUMSK","SHKZG","GSBER","PARGB","MWSKZ","QSSKZ","DMBTR","WRBTR","KZBTR","PSWBT","PSWSL","TXBHW","TXBFW","MWSTS","WMWST","HWBAS","FWBAS","HWZUZ","FWZUZ","SHZUZ","STEKZ","MWART","TXGRP","KTOSL","QSSHB","KURSR","GBETR","BDIFF","BDIF2","VALUT","ZUONR","SGTXT","ZINKZ","VBUND","BEWAR","ALTKT","VORGN","FDLEV","FDGRP","FDWBT","FDTAG","FKONT","KOKRS","KOSTL","PROJN","AUFNR","VBELN","VBEL2","POSN2","ETEN2","ANLN1","ANLN2","ANBWA","BZDAT","PERNR","XUMSW","XHRES","XKRES","XOPVW","XCPDD","XSKST","XSAUF","XSPRO","XSERG","XFAKT","XUMAN","XANET","XSKRL","XINVE","XPANZ","XAUTO","XNCOP","XZAHL","SAKNR","HKONT","KUNNR","LIFNR","FILKD","XBILK","GVTYP","HZUON","ZFBDT","ZTERM","ZBD1T","ZBD2T","ZBD3T","ZBD1P","ZBD2P","SKFBT","SKNTO","WSKTO","ZLSCH","ZLSPR","ZBFIX","HBKID","BVTYP","NEBTR","MWSK1","DMBT1","WRBT1","MWSK2","DMBT2","WRBT2","MWSK3","DMBT3","WRBT3","REBZG","REBZJ","REBZZ","REBZT","ZOLLT","ZOLLD","LZBKZ","LANDL","DIEKZ","SAMNR","ABPER","VRSKZ","VRSDT","DISBN","DISBJ","DISBZ","WVERW","ANFBN","ANFBJ","ANFBU","ANFAE","BLNBT","BLNKZ","BLNPZ","MSCHL","MANSP","MADAT","MANST","MABER","ESRNR","ESRRE","ESRPZ","KLIBT","QSZNR","QBSHB","QSFBT","NAVHW","NAVFW","MATNR","WERKS","MENGE","MEINS","ERFMG","ERFME","BPMNG","BPRME","EBELN","EBELP","ZEKKN","ELIKZ","VPRSV","PEINH","BWKEY","BWTAR","BUSTW","REWRT","REWWR","BONFB","BUALT","PSALT","NPREI","TBTKZ","SPGRP","SPGRM","SPGRT","SPGRG","SPGRV","SPGRQ","STCEG","EGBLD","EGLLD","RSTGR","RYACQ","RPACQ","RDIFF","RDIF2","PRCTR","XHKOM","VNAME","RECID","EGRUP","VPTNR","VERTT","VERTN","VBEWA","DEPOT","TXJCD","IMKEY","DABRZ","POPTS","FIPOS","KSTRG","NPLNR","AUFPL","APLZL","PROJK","PAOBJNR","PASUBNR","SPGRS","SPGRC","BTYPE","ETYPE","XEGDR","LNRAN","HRKFT","DMBE2","DMBE3","DMB21","DMB22","DMB23","DMB31","DMB32","DMB33","MWST2","MWST3","NAVH2","NAVH3","SKNT2","SKNT3","BDIF3","RDIF3","HWMET","GLUPM","XRAGL","UZAWE","LOKKT","FISTL","GEBER","STBUK","TXBH2","TXBH3","PPRCT","XREF1","XREF2","KBLNR","KBLPOS","STTAX","FKBER","OBZEI","XNEGP","RFZEI","CCBTC","KKBER","EMPFB","XREF3","DTWS1","DTWS2","DTWS3","DTWS4","GRICD","GRIRG","GITYP","XPYPR","KIDNO","ABSBT","IDXSP","LINFV","KONTT","KONTL","TXDAT","AGZEI","PYCUR","PYAMT","BUPLA","SECCO","LSTAR","CESSION_KZ","PRZNR","PPDIFF","PPDIF2","PPDIF3","PENLC1","PENLC2","PENLC3","PENFC","PENDAYS","PENRC","GRANT_NBR","SCTAX","FKBER_LONG","GMVKZ","SRTYPE","INTRENO","MEASURE","AUGGJ","PPA_EX_IND","ZZSPREG","ZZBUSPARTN","ZZCHAN","ZZPRODUCT","ZZLOCA","ZZLOB","ZZUSERFLD1","ZZUSERFLD2","ZZUSERFLD3","ZZSTATE","ZZREGION","DOCLN","SEGMENT","PSEGMENT","PFKBER","HKTID","KSTAR","XLGCLR","PEROP_BEG","PEROP_END","FASTPAY","PRODPER"]
bseg_primary_keys = [ "MANDT","BUKRS","BELNR","GJAHR","BUZEI"]

schema_old = "TEAM1_OLD"
schema_new = "TEAM1_NEW"

query_schema_1 = """ CREATE SCHEMA TEAM1_OLD """ 
query_schema_2 = """ CREATE SCHEMA TEAM1_NEW """

ACDOCA = """CREATE COLUMN TABLE "SAPISP"."ACDOCA" ("RCLNT" NVARCHAR(3) DEFAULT '000' NOT NULL , "RLDNR" NVARCHAR(2) DEFAULT '' NOT NULL , "RBUKRS" NVARCHAR(4) DEFAULT '' NOT NULL , "GJAHR" NVARCHAR(4) DEFAULT '0000' NOT NULL , "BELNR" NVARCHAR(10) DEFAULT '' NOT NULL , "DOCLN" NVARCHAR(6) DEFAULT '' NOT NULL , "RYEAR" NVARCHAR(4) DEFAULT '0000' NOT NULL , "RRCTY" NVARCHAR(1) DEFAULT '' NOT NULL , "RMVCT" NVARCHAR(3) DEFAULT '' NOT NULL , "VORGN" NVARCHAR(4) DEFAULT '' NOT NULL , "VRGNG" NVARCHAR(4) DEFAULT '' NOT NULL , "BTTYPE" NVARCHAR(4) DEFAULT '' NOT NULL , "AWTYP" NVARCHAR(5) DEFAULT '' NOT NULL , "AWSYS" NVARCHAR(10) DEFAULT '' NOT NULL , "AWORG" NVARCHAR(10) DEFAULT '' NOT NULL , "AWREF" NVARCHAR(10) DEFAULT '' NOT NULL , "AWITEM" NVARCHAR(6) DEFAULT '000000' NOT NULL , "AWITGRP" NVARCHAR(6) DEFAULT '000000' NOT NULL , "SUBTA" NVARCHAR(6) DEFAULT '000000' NOT NULL , "XREVERSING" NVARCHAR(1) DEFAULT '' NOT NULL , "XREVERSED" NVARCHAR(1) DEFAULT '' NOT NULL , "XTRUEREV" NVARCHAR(1) DEFAULT '' NOT NULL , "AWTYP_REV" NVARCHAR(5) DEFAULT '' NOT NULL , "AWORG_REV" NVARCHAR(10) DEFAULT '' NOT NULL , "AWREF_REV" NVARCHAR(10) DEFAULT '' NOT NULL , "SUBTA_REV" NVARCHAR(6) DEFAULT '000000' NOT NULL , "XSETTLING" NVARCHAR(1) DEFAULT '' NOT NULL , "XSETTLED" NVARCHAR(1) DEFAULT '' NOT NULL , "PREC_AWTYP" NVARCHAR(5) DEFAULT '' NOT NULL , "PREC_AWORG" NVARCHAR(10) DEFAULT '' NOT NULL , "PREC_AWREF" NVARCHAR(10) DEFAULT '' NOT NULL , "PREC_AWITEM" NVARCHAR(6) DEFAULT '000000' NOT NULL , "PREC_SUBTA" NVARCHAR(6) DEFAULT '000000' NOT NULL , "RTCUR" NVARCHAR(5) DEFAULT '' NOT NULL , "RWCUR" NVARCHAR(5) DEFAULT '' NOT NULL , "RHCUR" NVARCHAR(5) DEFAULT '' NOT NULL , "RKCUR" NVARCHAR(5) DEFAULT '' NOT NULL , "ROCUR" NVARCHAR(5) DEFAULT '' NOT NULL , "RVCUR" NVARCHAR(5) DEFAULT '' NOT NULL , "RCO_OCUR" NVARCHAR(5) DEFAULT '' NOT NULL , "RUNIT" NVARCHAR(3) DEFAULT '' NOT NULL , "RVUNIT" NVARCHAR(3) DEFAULT '' NOT NULL , "RRUNIT" NVARCHAR(3) DEFAULT '' NOT NULL , "QUNIT1" NVARCHAR(3) DEFAULT '' NOT NULL , "QUNIT2" NVARCHAR(3) DEFAULT '' NOT NULL , "QUNIT3" NVARCHAR(3) DEFAULT '' NOT NULL , "RACCT" NVARCHAR(10) DEFAULT '' NOT NULL , "RCNTR" NVARCHAR(10) DEFAULT '' NOT NULL , "PRCTR" NVARCHAR(10) DEFAULT '' NOT NULL , "RFAREA" NVARCHAR(16) DEFAULT '' NOT NULL , "RBUSA" NVARCHAR(4) DEFAULT '' NOT NULL , "KOKRS" NVARCHAR(4) DEFAULT '' NOT NULL , "SEGMENT" NVARCHAR(10) DEFAULT '' NOT NULL , "SCNTR" NVARCHAR(10) DEFAULT '' NOT NULL , "PPRCTR" NVARCHAR(10) DEFAULT '' NOT NULL , "SFAREA" NVARCHAR(16) DEFAULT '' NOT NULL , "SBUSA" NVARCHAR(4) DEFAULT '' NOT NULL , "RASSC" NVARCHAR(6) DEFAULT '' NOT NULL , "PSEGMENT" NVARCHAR(10) DEFAULT '' NOT NULL , "TSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "WSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "OSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "VSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KFSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "PSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "PFSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "CO_OSL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HSALK3" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KSALK3" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "OSALK3" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "VSALK3" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HSALKV" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KSALKV" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "OSALKV" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "VSALKV" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HPVPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KPVPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "OPVPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "VPVPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HSTPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KSTPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "OSTPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "VSTPRS" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HSLALT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KSLALT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "OSLALT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "VSLALT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HSLEXT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "KSLEXT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "OSLEXT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "VSLEXT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HVKWRT" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "HVKSAL" DECIMAL(23,2) CS_FIXED DEFAULT 0 NOT NULL , "MSL" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "MFSL" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "VMSL" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "VMFSL" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "RMSL" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "QUANT1" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "QUANT2" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "QUANT3" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "LBKUM" DECIMAL(23,3) CS_FIXED DEFAULT 0 NOT NULL , "DRCRK" NVARCHAR(1) DEFAULT '' NOT NULL , "POPER" NVARCHAR(3) DEFAULT '000' NOT NULL , "PERIV" NVARCHAR(2) DEFAULT '' NOT NULL , "FISCYEARPER" NVARCHAR(7) DEFAULT '0000000' NOT NULL , "BUDAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "BLDAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "BLART" NVARCHAR(2) DEFAULT '' NOT NULL , "BUZEI" NVARCHAR(3) DEFAULT '000' NOT NULL , "ZUONR" NVARCHAR(18) DEFAULT '' NOT NULL , "BSCHL" NVARCHAR(2) DEFAULT '' NOT NULL , "BSTAT" NVARCHAR(1) DEFAULT '' NOT NULL , "LINETYPE" NVARCHAR(5) DEFAULT '' NOT NULL , "KTOSL" NVARCHAR(3) DEFAULT '' NOT NULL , "SLALITTYPE" NVARCHAR(5) DEFAULT '00000' NOT NULL , "XSPLITMOD" NVARCHAR(1) DEFAULT '' NOT NULL , "USNAM" NVARCHAR(12) DEFAULT '' NOT NULL , "TIMESTAMP" DECIMAL(15,0) CS_FIXED DEFAULT 0 NOT NULL , "EPRCTR" NVARCHAR(10) DEFAULT '' NOT NULL , "RHOART" NVARCHAR(2) DEFAULT '00' NOT NULL , "GLACCOUNT_TYPE" NVARCHAR(1) DEFAULT '' NOT NULL , "KTOPL" NVARCHAR(4) DEFAULT '' NOT NULL , "LOKKT" NVARCHAR(10) DEFAULT '' NOT NULL , "KTOP2" NVARCHAR(4) DEFAULT '' NOT NULL , "REBZG" NVARCHAR(10) DEFAULT '' NOT NULL , "REBZJ" NVARCHAR(4) DEFAULT '0000' NOT NULL , "REBZZ" NVARCHAR(3) DEFAULT '000' NOT NULL , "REBZT" NVARCHAR(1) DEFAULT '' NOT NULL , "RBEST" NVARCHAR(3) DEFAULT '000' NOT NULL , "EBELN" NVARCHAR(10) DEFAULT '' NOT NULL , "EBELP" NVARCHAR(5) DEFAULT '00000' NOT NULL , "ZEKKN" NVARCHAR(2) DEFAULT '00' NOT NULL , "SGTXT" NVARCHAR(50) DEFAULT '' NOT NULL , "KDAUF" NVARCHAR(10) DEFAULT '' NOT NULL , "KDPOS" NVARCHAR(6) DEFAULT '000000' NOT NULL , "MATNR" NVARCHAR(18) DEFAULT '' NOT NULL , "WERKS" NVARCHAR(4) DEFAULT '' NOT NULL , "LIFNR" NVARCHAR(10) DEFAULT '' NOT NULL , "KUNNR" NVARCHAR(10) DEFAULT '' NOT NULL , "KOART" NVARCHAR(1) DEFAULT '' NOT NULL , "UMSKZ" NVARCHAR(1) DEFAULT '' NOT NULL , "MWSKZ" NVARCHAR(2) DEFAULT '' NOT NULL , "HBKID" NVARCHAR(5) DEFAULT '' NOT NULL , "HKTID" NVARCHAR(5) DEFAULT '' NOT NULL , "XOPVW" NVARCHAR(1) DEFAULT '' NOT NULL , "AUGDT" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "AUGBL" NVARCHAR(10) DEFAULT '' NOT NULL , "AUGGJ" NVARCHAR(4) DEFAULT '0000' NOT NULL , "AFABE" NVARCHAR(2) DEFAULT '00' NOT NULL , "ANLN1" NVARCHAR(12) DEFAULT '' NOT NULL , "ANLN2" NVARCHAR(4) DEFAULT '' NOT NULL , "BZDAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "ANBWA" NVARCHAR(3) DEFAULT '' NOT NULL , "MOVCAT" NVARCHAR(2) DEFAULT '' NOT NULL , "DEPR_PERIOD" NVARCHAR(3) DEFAULT '000' NOT NULL , "ANLGR" NVARCHAR(12) DEFAULT '' NOT NULL , "ANLGR2" NVARCHAR(4) DEFAULT '' NOT NULL , "SETTLEMENT_RULE" NVARCHAR(3) DEFAULT '000' NOT NULL , "KALNR" NVARCHAR(12) DEFAULT '000000000000' NOT NULL , "VPRSV" NVARCHAR(1) DEFAULT '' NOT NULL , "MLAST" NVARCHAR(1) DEFAULT '' NOT NULL , "KZBWS" NVARCHAR(1) DEFAULT '' NOT NULL , "XOBEW" NVARCHAR(1) DEFAULT '' NOT NULL , "SOBKZ" NVARCHAR(1) DEFAULT '' NOT NULL , "VTSTAMP" DECIMAL(21,7) CS_FIXED DEFAULT 0 NOT NULL , "MAT_KDAUF" NVARCHAR(10) DEFAULT '' NOT NULL , "MAT_KDPOS" NVARCHAR(6) DEFAULT '000000' NOT NULL , "MAT_PSPNR" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "MAT_PS_POSID" NVARCHAR(24) DEFAULT '' NOT NULL , "MAT_LIFNR" NVARCHAR(10) DEFAULT '' NOT NULL , "BWTAR" NVARCHAR(10) DEFAULT '' NOT NULL , "BWKEY" NVARCHAR(4) DEFAULT '' NOT NULL , "HPEINH" DECIMAL(5,0) CS_FIXED DEFAULT 0 NOT NULL , "KPEINH" DECIMAL(5,0) CS_FIXED DEFAULT 0 NOT NULL , "OPEINH" DECIMAL(5,0) CS_FIXED DEFAULT 0 NOT NULL , "VPEINH" DECIMAL(5,0) CS_FIXED DEFAULT 0 NOT NULL , "MLPTYP" NVARCHAR(4) DEFAULT '' NOT NULL , "MLCATEG" NVARCHAR(2) DEFAULT '' NOT NULL , "QSBVALT" NVARCHAR(12) DEFAULT '000000000000' NOT NULL , "QSPROCESS" NVARCHAR(12) DEFAULT '000000000000' NOT NULL , "PERART" NVARCHAR(2) DEFAULT '' NOT NULL , "RACCT_SENDER" NVARCHAR(10) DEFAULT '' NOT NULL , "ACCAS_SENDER" NVARCHAR(30) DEFAULT '' NOT NULL , "ACCASTY_SENDER" NVARCHAR(2) DEFAULT '' NOT NULL , "OBJNR" NVARCHAR(22) DEFAULT '' NOT NULL , "HRKFT" NVARCHAR(14) DEFAULT '' NOT NULL , "HKGRP" NVARCHAR(4) DEFAULT '' NOT NULL , "PAROB1" NVARCHAR(22) DEFAULT '' NOT NULL , "PAROBSRC" NVARCHAR(1) DEFAULT '' NOT NULL , "USPOB" NVARCHAR(22) DEFAULT '' NOT NULL , "CO_BELKZ" NVARCHAR(1) DEFAULT '' NOT NULL , "CO_BEKNZ" NVARCHAR(1) DEFAULT '' NOT NULL , "BELTP" NVARCHAR(1) DEFAULT '0' NOT NULL , "MUVFLG" NVARCHAR(1) DEFAULT '0' NOT NULL , "GKONT" NVARCHAR(10) DEFAULT '' NOT NULL , "GKOAR" NVARCHAR(1) DEFAULT '' NOT NULL , "ERLKZ" NVARCHAR(1) DEFAULT '' NOT NULL , "PERNR" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "PAOBJNR" NVARCHAR(10) DEFAULT '0000000000' NOT NULL , "XPAOBJNR_CO_REL" NVARCHAR(1) DEFAULT '' NOT NULL , "SCOPE" NVARCHAR(2) DEFAULT '' NOT NULL , "LOGSYSO" NVARCHAR(10) DEFAULT '' NOT NULL , "PBUKRS" NVARCHAR(4) DEFAULT '' NOT NULL , "PSCOPE" NVARCHAR(2) DEFAULT '' NOT NULL , "LOGSYSP" NVARCHAR(10) DEFAULT '' NOT NULL , "BWSTRAT" NVARCHAR(1) DEFAULT '' NOT NULL , "OBJNR_HK" NVARCHAR(22) DEFAULT '' NOT NULL , "AUFNR_ORG" NVARCHAR(12) DEFAULT '' NOT NULL , "UKOSTL" NVARCHAR(10) DEFAULT '' NOT NULL , "ULSTAR" NVARCHAR(6) DEFAULT '' NOT NULL , "UPRZNR" NVARCHAR(12) DEFAULT '' NOT NULL , "ACCAS" NVARCHAR(30) DEFAULT '' NOT NULL , "ACCASTY" NVARCHAR(2) DEFAULT '' NOT NULL , "LSTAR" NVARCHAR(6) DEFAULT '' NOT NULL , "AUFNR" NVARCHAR(12) DEFAULT '' NOT NULL , "AUTYP" NVARCHAR(2) DEFAULT '00' NOT NULL , "PS_POSID" NVARCHAR(24) DEFAULT '' NOT NULL , "PS_PSPID" NVARCHAR(24) DEFAULT '' NOT NULL , "NPLNR" NVARCHAR(12) DEFAULT '' NOT NULL , "NPLNR_VORGN" NVARCHAR(4) DEFAULT '' NOT NULL , "PRZNR" NVARCHAR(12) DEFAULT '' NOT NULL , "KSTRG" NVARCHAR(12) DEFAULT '' NOT NULL , "BEMOT" NVARCHAR(2) DEFAULT '' NOT NULL , "QMNUM" NVARCHAR(12) DEFAULT '' NOT NULL , "ERKRS" NVARCHAR(4) DEFAULT '' NOT NULL , "PACCAS" NVARCHAR(30) DEFAULT '' NOT NULL , "PACCASTY" NVARCHAR(2) DEFAULT '' NOT NULL , "PLSTAR" NVARCHAR(6) DEFAULT '' NOT NULL , "PAUFNR" NVARCHAR(12) DEFAULT '' NOT NULL , "PAUTYP" NVARCHAR(2) DEFAULT '00' NOT NULL , "PPS_POSID" NVARCHAR(24) DEFAULT '' NOT NULL , "PPS_PSPID" NVARCHAR(24) DEFAULT '' NOT NULL , "PKDAUF" NVARCHAR(10) DEFAULT '' NOT NULL , "PKDPOS" NVARCHAR(6) DEFAULT '000000' NOT NULL , "PPAOBJNR" NVARCHAR(10) DEFAULT '0000000000' NOT NULL , "PNPLNR" NVARCHAR(12) DEFAULT '' NOT NULL , "PNPLNR_VORGN" NVARCHAR(4) DEFAULT '' NOT NULL , "PPRZNR" NVARCHAR(12) DEFAULT '' NOT NULL , "PKSTRG" NVARCHAR(12) DEFAULT '' NOT NULL , "CO_ACCASTY_N1" NVARCHAR(2) DEFAULT '' NOT NULL , "CO_ACCASTY_N2" NVARCHAR(2) DEFAULT '' NOT NULL , "CO_ACCASTY_N3" NVARCHAR(2) DEFAULT '' NOT NULL , "CO_ZLENR" NVARCHAR(3) DEFAULT '000' NOT NULL , "CO_BELNR" NVARCHAR(10) DEFAULT '' NOT NULL , "CO_BUZEI" NVARCHAR(3) DEFAULT '000' NOT NULL , "FKART" NVARCHAR(4) DEFAULT '' NOT NULL , "VKORG" NVARCHAR(4) DEFAULT '' NOT NULL , "VTWEG" NVARCHAR(2) DEFAULT '' NOT NULL , "SPART" NVARCHAR(2) DEFAULT '' NOT NULL , "MATNR_COPA" NVARCHAR(18) DEFAULT '' NOT NULL , "MATKL" NVARCHAR(9) DEFAULT '' NOT NULL , "KDGRP" NVARCHAR(2) DEFAULT '' NOT NULL , "ACDOC_COPA_EEW_DUMMY_PA" NVARCHAR(1) DEFAULT '' NOT NULL , "LAND1_PA" NVARCHAR(3) DEFAULT '' NOT NULL , "KUNNV_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "AUFNU_PA" NVARCHAR(12) DEFAULT '' NOT NULL , "PRONR_PA" NVARCHAR(8) DEFAULT '' NOT NULL , "DISTC_PA" NVARCHAR(3) DEFAULT '' NOT NULL , "DISTP_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "DIVIS_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "SYSTE_PA" NVARCHAR(3) DEFAULT '' NOT NULL , "OTYPE_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "CONCE_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "BRANC_PA" NVARCHAR(4) DEFAULT '' NOT NULL , "DISTR_PA" NVARCHAR(2) DEFAULT '' NOT NULL , "REGIC_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "REGAR_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "REGI_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "SAPRE_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "SAPRA_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "CONTP_PA" NVARCHAR(2) DEFAULT '' NOT NULL , "LFREC_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "PROGR_PA" NVARCHAR(2) DEFAULT '' NOT NULL , "KEYCO_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "RCOMP_PA" NVARCHAR(6) DEFAULT '' NOT NULL , "VVACO_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "VVDI2_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "VVCCE_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "VVSUN_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "KATR3_PA" NVARCHAR(2) DEFAULT '' NOT NULL , "JMZAH_PA" NVARCHAR(6) DEFAULT '000000' NOT NULL , "WWUMS_PA" NVARCHAR(15) DEFAULT '' NOT NULL , "WWEVT_PA" NVARCHAR(6) DEFAULT '' NOT NULL , "WWMBE_PA" NVARCHAR(12) DEFAULT '' NOT NULL , "VKGRP_PA" NVARCHAR(3) DEFAULT '' NOT NULL , "VKBUR_PA" NVARCHAR(4) DEFAULT '' NOT NULL , "KATR5_PA" NVARCHAR(2) DEFAULT '' NOT NULL , "KATR8_PA" NVARCHAR(3) DEFAULT '' NOT NULL , "WWMSE_PA" NVARCHAR(5) DEFAULT '' NOT NULL , "WWIND_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "WWSMT_PA" NVARCHAR(18) DEFAULT '' NOT NULL , "WWDOC_PA" NVARCHAR(2) DEFAULT '' NOT NULL , "WWRBN_PA" NVARCHAR(10) DEFAULT '' NOT NULL , "RE_BUKRS" NVARCHAR(4) DEFAULT '' NOT NULL , "RE_ACCOUNT" NVARCHAR(10) DEFAULT '' NOT NULL , "FIKRS" NVARCHAR(4) DEFAULT '' NOT NULL , "FISTL" NVARCHAR(16) DEFAULT '' NOT NULL , "MEASURE" NVARCHAR(24) DEFAULT '' NOT NULL , "RFUND" NVARCHAR(10) DEFAULT '' NOT NULL , "RGRANT_NBR" NVARCHAR(20) DEFAULT '' NOT NULL , "RBUDGET_PD" NVARCHAR(10) DEFAULT '' NOT NULL , "SFUND" NVARCHAR(10) DEFAULT '' NOT NULL , "SGRANT_NBR" NVARCHAR(20) DEFAULT '' NOT NULL , "SBUDGET_PD" NVARCHAR(10) DEFAULT '' NOT NULL , "VNAME" NVARCHAR(6) DEFAULT '' NOT NULL , "EGRUP" NVARCHAR(3) DEFAULT '' NOT NULL , "RECID" NVARCHAR(2) DEFAULT '' NOT NULL , "VPTNR" NVARCHAR(10) DEFAULT '' NOT NULL , "BTYPE" NVARCHAR(2) DEFAULT '' NOT NULL , "ETYPE" NVARCHAR(3) DEFAULT '' NOT NULL , "PRODPER" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "SWENR" NVARCHAR(8) DEFAULT '' NOT NULL , "SGENR" NVARCHAR(8) DEFAULT '' NOT NULL , "SGRNR" NVARCHAR(8) DEFAULT '' NOT NULL , "SMENR" NVARCHAR(8) DEFAULT '' NOT NULL , "RECNNR" NVARCHAR(13) DEFAULT '' NOT NULL , "SNKSL" NVARCHAR(4) DEFAULT '' NOT NULL , "SEMPSL" NVARCHAR(5) DEFAULT '' NOT NULL , "DABRZ" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "PSWENR" NVARCHAR(8) DEFAULT '' NOT NULL , "PSGENR" NVARCHAR(8) DEFAULT '' NOT NULL , "PSGRNR" NVARCHAR(8) DEFAULT '' NOT NULL , "PSMENR" NVARCHAR(8) DEFAULT '' NOT NULL , "PRECNNR" NVARCHAR(13) DEFAULT '' NOT NULL , "PSNKSL" NVARCHAR(4) DEFAULT '' NOT NULL , "PSEMPSL" NVARCHAR(5) DEFAULT '' NOT NULL , "PDABRZ" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "ACDOC_EEW_DUMMY" NVARCHAR(1) DEFAULT '' NOT NULL , "ZZSEEM_ORIG" NVARCHAR(22) DEFAULT '' NOT NULL , "ZZUMBKZ" NVARCHAR(1) DEFAULT '' NOT NULL , "ZZ_LOCATION" NVARCHAR(1) DEFAULT '' NOT NULL , "ZZREF1" NVARCHAR(22) DEFAULT '' NOT NULL , "ZZREF2" NVARCHAR(22) DEFAULT '0000000000000000000000' NOT NULL , "ZZREF3" NVARCHAR(10) DEFAULT '' NOT NULL , "ZZREF4" NVARCHAR(10) DEFAULT '0000000000' NOT NULL , "ZZSPLIT" NVARCHAR(10) DEFAULT '' NOT NULL , "MIG_SOURCE" NVARCHAR(1) DEFAULT '' NOT NULL , "MIG_DOCLN" NVARCHAR(6) DEFAULT '' NOT NULL , "_DATAAGING" NVARCHAR(8) DEFAULT '00000000' NOT NULL , "CO_REFBZ" NVARCHAR(3) DEFAULT '000' NOT NULL , "PREC_AWMULT" VARBINARY(16) CS_RAW) UNLOAD PRIORITY 5  AUTO MERGE  WITH PARAMETERS ('PARTITION_SPEC' = 'RANGE RBUKRS 0000-0002,0002-0024,0024-9999,*; RANGE[TIME SELECTION: NO UNIQUE CHECK] _DATAAGING 00000000,00010101-20110101,20110101-20120101,20120101-20130101,20130101-20140101,20140101-20150101,20150101-20160101');
ALTER TABLE "SAPISP"."ACDOCA" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$RCLNT$RBUKRS$BELNR$GJAHR$','RCLNT','RBUKRS','BELNR','GJAHR'));
ALTER TABLE "SAPISP"."ACDOCA" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$RCLNT$RBUKRS$BELNR$GJAHR$BUZEI$','RCLNT','RBUKRS','BELNR','GJAHR','BUZEI'));
ALTER TABLE "SAPISP"."ACDOCA" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$RCLNT$RBUKRS$RLDNR$','RCLNT','RBUKRS','RLDNR'));
ALTER TABLE "SAPISP"."ACDOCA" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$BELNR$DOCLN$GJAHR$RBUKRS$','BELNR','DOCLN','GJAHR','RBUKRS'));
CREATE INDEX "ACDOCA~ONR" ON "SAPISP"."ACDOCA" ( "OBJNR" ASC );
CREATE INDEX "ACDOCA~ZJW" ON "SAPISP"."ACDOCA" ( "CO_BELNR" ASC );
CREATE INDEX "ACDOCA~BEL" ON "SAPISP"."ACDOCA" ( "BELNR" ASC );
CREATE INDEX "ACDOCA~ANL" ON "SAPISP"."ACDOCA" ( "ANLN1" ASC )
"""

connector.execute(query_schema_1)
connector.execute(query_schema_2)
 
# Creates the desired databases
create_table(schema_old + ".BKPF", "ROW", bkpf_columns, bkpf_primary_keys)
create_table(schema_old + ".BSEG", "ROW", bseg_columns, bseg_primary_keys)
create_table(schema_new + ".BKPF", "COLUMN", bkpf_columns, bkpf_primary_keys)
create_table(schema_new + ".BSEG", "COLUMN", bseg_columns, bseg_primary_keys)

# Create reduced databases
create_table(schema_old + ".BKPF_R", "ROW", bkpf_reduced, bkpf_primary_keys)
create_table(schema_old + ".BSEG_R", "ROW", bseg_reduced, bseg_primary_keys)
create_table(schema_old + ".GLT0_R", "ROW", glt0_reduced, glt0_primary_keys)
create_table(schema_new + ".ACDOCA_R", "COLUMN", acdoca_reduced, acdoca_primary_keys)

print ("Insert OLD BKPF")
#benchmark(20, dummy_insert, schema_old + ".BKPF", bkpf_columns)

print ("Insert NEW BKPF")
#benchmark(20, dummy_insert, schema_new + ".BKPF", bkpf_columns)

print ("Insert OLD BSEG")
#benchmark(20, dummy_insert, schema_old + ".BSEG", bseg_columns)

print ("Insert NEW BSEG")
#benchmark(20, dummy_insert, schema_new + ".BSEG", bseg_columns)

print("Starting real benchmarks")
data = cid.create_data(20)
benchmark_old_schema(20, data)

connector.dropTable('TEAM1_OLD.', 'BKPF')
connector.dropTable('TEAM1_OLD.', 'BSEG')
connector.dropTable('TEAM1_NEW.', 'BKPF')
connector.dropTable('TEAM1_NEW.', 'BSEG')

connector.dropTable('TEAM1_OLD.', 'BKPF_R')
connector.dropTable('TEAM1_OLD.', 'BSEG_R')
connector.dropTable('TEAM1_OLD.', 'GLT0_R')
connector.dropTable('TEAM1_NEW.', 'ACDOCA_R')

connector.dropSchema(schema_old)
connector.dropSchema(schema_new)