#!/usr/bin/env python
# -*- coding: utf-8 -*-

import connector

# Create Schemata:

schema_old = "TEAM1_OLD"
schema_new = "TEAM1_NEW"

query_schema_1 = """ CREATE SCHEMA TEAM1_OLD """ 
query_schema_2 = """ CREATE SCHEMA TEAM1_NEW """

connector.execute(query_schema_1)
connector.execute(query_schema_2)
 

# Creates the desired databases
create_bkpf = """
        MANDT Integer,
        BUKRS Integer,
        BELNR Integer,
        GJAHR Integer,
        BLART Integer,
        BLDAT Integer,
        BUDAT Integer,
        MONAT Integer,
        CPUDT Integer,
        CPUTM Integer,
        AEDAT Integer,
        UPDDT Integer,
        WWERT Integer,
        USNAM Integer,
        TCODE Integer,
        BVORG Integer,
        XBLNR Integer,
        DBBLG Integer,
        STBLG Integer,
        STJAH Integer,
        BKTXT Integer,
        WAERS Integer,
        KURSF Integer,
        KZWRS Integer,
        KZKRS Integer,
        BSTAT Integer,
        XNETB Integer,
        FRATH Integer,
        XRUEB Integer,
        GLVOR Integer,
        GRPID Integer,
        DOKID Integer,
        ARCID Integer,
        IBLAR Integer,
        AWTYP Integer,
        AWKEY Integer,
        FIKRS Integer,
        HWAER Integer,
        HWAE2 Integer,
        HWAE3 CHAR(5),
        KURS2 Integer,
        KURS3 Integer,
        BASW2 Integer,
        BASW3 Integer,
        UMRD2 Integer,
        UMRD3 Integer,
        XSTOV Integer,
        STODT DATE,
        XMWST Integer,
        CURT2 Integer,
        CURT3 Integer,
        KUTY2 Integer,
        KUTY3 Integer,
        XSNET Integer,
        AUSBK Integer,
        XUSVR Integer,
        DUEFL Integer,
        AWSYS Integer,
        TXKRS Integer,
        LOTKZ Integer,
        XWVOF Integer,
        STGRD Integer,
        PPNAM Integer,
        BRNCH Integer,
        NUMPG Integer,
        ADISC Integer,
        XREF1_HD Integer,
        XREF2_HD Integer,
        XREVERSAL Integer,
        REINDAT Integer,RLDNR Integer,
        LDGRP Integer,
        PROPMANO Integer,
        XBLNR_ALT Integer,
        VATDATE Integer,
        PSOTY Integer,
        PSOAK Integer,
        PSOKS Integer,
        PSOSG Integer,
        PSOFN Integer,
        INTFORM Integer,
        INTDATE Integer,
        PSOBT Integer,
        PSOZL Integer,
        PSODT Integer,PSOTM Integer,
        FM_UMART Integer,
        CCINS Integer,
        CCNUM Integer,
        SSBLK Integer,
        BATCH Integer,
        SNAME Integer,
        SAMPLED Integer,
        EXCLUDE_FLAG Integer,
        BLIND Integer,
        OFFSET_STATUS Integer,
        OFFSET_REFER_DAT Integer,
        PENRC Integer,
        KNUMV Integer,
        
        PRIMARY KEY (MANDT,BUKRS,BELNR,GJAHR)
     ); 
     """
create_old_bkpf = """ 
    CREATE ROW TABLE TEAM1_OLD.BKPF (
""" + create_bkpf

create_new_bkpf = """ 
    CREATE COLUMN TABLE TEAM1_NEW.BKPF (
""" + create_bkpf



create_bseg = """
        MANDT Integer,
        BUKRS Integer,
        BELNR Integer,
        GJAHR Integer,
        BUZEI Integer,
        BUZID Integer,
        AUGDT Integer,
        AUGCP Integer,
        AUGBL Integer,
        BSCHL Integer,
        KOART Integer,
        UMSKZ Integer,
        UMSKS Integer,
        ZUMSK Integer,
        SHKZG Integer,
        GSBER Integer,
        PARGB Integer,
        MWSKZ Integer,
        QSSKZ Integer,
        DMBTR Integer,
        WRBTR Integer,
        KZBTR Integer,
        PSWBT Integer,
        PSWSL Integer,
        TXBHW Integer,
        TXBFW Integer,
        MWSTS Integer,
        WMWST Integer,
        HWBAS Integer,
        FWBAS Integer,
        HWZUZ Integer,
        FWZUZ Integer,
        SHZUZ Integer,
        STEKZ Integer,
        MWART Integer,
        TXGRP Integer,
        KTOSL Integer,
        QSSHB Integer,
        KURSR Integer,
        GBETR Integer,
        BDIFF Integer,
        BDIF2 Integer,
        VALUT Integer,
        ZUONR Integer,
        SGTXT Integer,
        ZINKZ Integer,
        VBUND Integer,
        BEWAR Integer,
        ALTKT Integer,
        VORGN Integer,
        FDLEV Integer,
        FDGRP Integer,
        FDWBT Integer,
        FDTAG Integer,
        FKONT Integer,
        KOKRS Integer,
        KOSTL Integer,
        PROJN Integer,
        AUFNR Integer,
        VBELN Integer,
        VBEL2 Integer,
        POSN2 Integer,
        ETEN2 Integer,
        ANLN1 Integer,
        ANLN2 Integer,
        ANBWA Integer,
        BZDAT Integer,
        PERNR Integer,
        XUMSW Integer,
        XHRES Integer,
        XKRES Integer,
        XOPVW Integer,
        XCPDD Integer,
        XSKST Integer,
        XSAUF Integer,
        XSPRO Integer,
        XSERG Integer,
        XFAKT Integer,
        XUMAN Integer,
        XANET Integer,
        XSKRL Integer,
        XINVE Integer,
        XPANZ Integer,
        XAUTO Integer,
        XNCOP Integer,
        XZAHL Integer,
        SAKNR Integer,
        HKONT Integer,
        KUNNR Integer,
        LIFNR Integer,
        FILKD Integer,
        XBILK Integer,
        GVTYP Integer,
        HZUON Integer,
        ZFBDT Integer,
        ZTERM Integer,
        ZBD1T Integer,
        ZBD2T Integer,
        ZBD3T Integer,
        ZBD1P Integer,
        ZBD2P Integer,
        SKFBT Integer,
        SKNTO Integer,
        WSKTO Integer,
        ZLSCH Integer,
        ZLSPR Integer,
        ZBFIX Integer,
        HBKID Integer,
        BVTYP Integer,
        NEBTR Integer,
        MWSK1 Integer,
        DMBT1 Integer,
        WRBT1 Integer,
        MWSK2 Integer,
        DMBT2 Integer,
        WRBT2 Integer,
        MWSK3 Integer,
        DMBT3 Integer,
        WRBT3 Integer,
        REBZG Integer,
        REBZJ Integer,
        REBZZ Integer,
        REBZT Integer,
        ZOLLT Integer,
        ZOLLD Integer,
        LZBKZ Integer,
        LANDL Integer,
        DIEKZ Integer,
        SAMNR Integer,
        ABPER Integer,
        VRSKZ Integer,
        VRSDT Integer,
        DISBN Integer,
        DISBJ Integer,
        DISBZ Integer,
        WVERW Integer,
        ANFBN Integer,
        ANFBJ Integer,
        ANFBU Integer,
        ANFAE Integer,
        BLNBT Integer,
        BLNKZ Integer,
        BLNPZ Integer,
        MSCHL Integer,
        MANSP Integer,
        MADAT Integer,
        MANST Integer,
        MABER Integer,
        ESRNR Integer,
        ESRRE Integer,
        ESRPZ Integer,
        KLIBT Integer,
        QSZNR Integer,
        QBSHB Integer,
        QSFBT Integer,
        NAVHW Integer,
        NAVFW Integer,
        MATNR Integer,
        WERKS Integer,
        MENGE Integer,
        MEINS Integer,
        ERFMG Integer,
        ERFME Integer,
        BPMNG Integer,
        BPRME Integer,
        EBELN Integer,
        EBELP Integer,
        ZEKKN Integer,
        ELIKZ Integer,
        VPRSV Integer,
        PEINH Integer,
        BWKEY Integer,
        BWTAR Integer,
        BUSTW Integer,
        REWRT Integer,
        REWWR Integer,
        BONFB Integer,
        BUALT Integer,
        PSALT Integer,
        NPREI Integer,
        TBTKZ Integer,
        SPGRP Integer,
        SPGRM Integer,
        SPGRT Integer,
        SPGRG Integer,
        SPGRV Integer,
        SPGRQ Integer,
        STCEG Integer,
        EGBLD Integer,
        EGLLD Integer,
        RSTGR Integer,
        RYACQ Integer,
        RPACQ Integer,
        RDIFF Integer,
        RDIF2 Integer,
        PRCTR Integer,
        XHKOM Integer,
        VNAME Integer,
        RECID Integer,
        EGRUP Integer,
        VPTNR Integer,
        VERTT Integer,
        VERTN Integer,
        VBEWA Integer,
        DEPOT Integer,
        TXJCD Integer,
        IMKEY Integer,
        DABRZ Integer,
        POPTS Integer,
        FIPOS Integer,
        KSTRG Integer,
        NPLNR Integer,
        AUFPL Integer,
        APLZL Integer,
        PROJK Integer,
        PAOBJNR Integer,
        PASUBNR Integer,
        SPGRS Integer,
        SPGRC Integer,
        BTYPE Integer,
        ETYPE Integer,
        XEGDR Integer,
        LNRAN Integer,
        HRKFT Integer,
        DMBE2 Integer,
        DMBE3 Integer,
        DMB21 Integer,
        DMB22 Integer,
        DMB23 Integer,
        DMB31 Integer,
        DMB32 Integer,
        DMB33 Integer,
        MWST2 Integer,
        MWST3 Integer,
        NAVH2 Integer,
        NAVH3 Integer,
        SKNT2 Integer,
        SKNT3 Integer,
        BDIF3 Integer,
        RDIF3 Integer,
        HWMET Integer,
        GLUPM Integer,
        XRAGL Integer,
        UZAWE Integer,
        LOKKT Integer,
        FISTL Integer,
        GEBER Integer,
        STBUK Integer,
        TXBH2 Integer,
        TXBH3 Integer,
        PPRCT Integer,
        XREF1 Integer,
        XREF2 Integer,

        KBLNR Integer,
        KBLPOS Integer,
        STTAX Integer,
        FKBER Integer,
        OBZEI Integer,
        XNEGP Integer,
        RFZEI Integer,
        CCBTC Integer,
        KKBER Integer,
        EMPFB Integer,
        XREF3 Integer,
        DTWS1 Integer,
        DTWS2 Integer,
        DTWS3 Integer,
        DTWS4 Integer,
        GRICD Integer,
        GRIRG Integer,
        GITYP Integer,
        XPYPR Integer,
        KIDNO Integer,
        ABSBT Integer,
        IDXSP Integer,
        LINFV Integer,
        KONTT Integer,
        KONTL Integer,
        TXDAT Integer,
        AGZEI Integer,
        PYCUR Integer,
        PYAMT Integer,
        BUPLA Integer,
        SECCO Integer,
        LSTAR Integer,
        CESSION_KZ Integer,
        PRZNR Integer,
        PPDIFF Integer,
        PPDIF2 Integer,
        PPDIF3 Integer,
        PENLC1 Integer,
        PENLC2 Integer,
        PENLC3 Integer,
        PENFC Integer,
        PENDAYS Integer,
        PENRC Integer,
        GRANT_NBR Integer,
        SCTAX Integer,
        FKBER_LONG Integer,
        GMVKZ Integer,
        SRTYPE Integer,
        INTRENO Integer,
        MEASURE Integer,
        AUGGJ Integer,
        PPA_EX_IND Integer,
        ZZSPREG Integer,
        ZZBUSPARTN Integer,
        ZZCHAN Integer,
        ZZPRODUCT Integer,
        ZZLOCA Integer,
        ZZLOB Integer,
        ZZUSERFLD1 Integer,
        ZZUSERFLD2 Integer,
        ZZUSERFLD3 Integer,
        ZZSTATE Integer,
        ZZREGION Integer,
        DOCLN Integer,
        SEGMENT Integer,
        PSEGMENT Integer,
        PFKBER Integer,
        HKTID Integer,
        KSTAR Integer,
        XLGCLR Integer,
        PEROP_BEG Integer,
        PEROP_END Integer,
        FASTPAY Integer,
        PRODPER Integer,

        primary key (MANDT,BUKRS,BELNR,GJAHR,BUZEI)
    );
    """

create_old_bseg = """
    CREATE ROW TABLE TEAM1_OLD.BSEG (
""" + create_bseg

create_new_bseg = """
    CREATE COLUMN TABLE TEAM1_NEW.BSEG (
""" + create_bseg


connector.execute(create_old_bkpf)
connector.execute(create_old_bseg)
connector.execute(create_new_bkpf)
connector.execute(create_new_bseg)

connector.dropTable('TEAM1_OLD.', 'BKPF')
connector.dropTable('TEAM1_OLD.', 'BSEG')
connector.dropTable('TEAM1_NEW.', 'BKPF')
connector.dropTable('TEAM1_NEW.', 'BSEG')

connector.dropSchema(schema_old)
connector.dropSchema(schema_new)